/* eslint-disable @next/next/no-img-element */
import { getPropertyData } from "@/lib/data";
import { DEFAULTS, rankProperties } from "@/lib/finance";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export default async function RankingsPage({ searchParams }: { searchParams: Promise<{ q?: string; risk?: string; corridors?: string; yard?: string }> }) {
  const query = await searchParams;
  const search = (query.q ?? "").toLowerCase().trim();
  const { properties, fetchedAt } = await getPropertyData();
  const excludeCorridors = query.corridors !== "include";
  const ranked = rankProperties(properties).filter((deal) => (!search || `${deal.property.address} ${deal.property.owner}`.toLowerCase().includes(search)) && (query.risk !== "positive" || deal.cashFlow > 0) && (!excludeCorridors || !deal.property.inTransitCorridor) && (query.yard !== "strong" || deal.property.yardPotential === "Strong"));
  const best = ranked[0];
  return <div className="app-shell ranking-app"><aside className="sidebar"><div><div className="logo"><span>PE</span><div>Property<br/>Extraction</div></div><nav><a href="/">Prospects</a><a href="/sixplexes">Sixplex prospects</a><a href="/garages">Garage deals</a><a className="active" href="/rankings">Deal rankings</a><a href={best ? `/analyze?parcel=${best.property.parcelId}` : "/analyze"}>Buy Lab</a><a href="#methodology">Ranking method</a></nav></div><form action="/api/logout" method="post"><button className="logout">Sign out</button></form></aside>
    <main className="workspace model-workspace"><header><div><p className="eyebrow">RISK-ADJUSTED FOURPLEX RANKING</p><h1>Which deal would I pursue first?</h1><p className="muted">A preliminary financial screen across every Anchorage fourplex in the public parcel layer.</p></div><div className="live"><i/> Live municipal data<br/><small>Updated {new Date(fetchedAt).toLocaleString("en-US", { timeZone: "America/Anchorage" })}</small></div></header>
      {best && <section className="best-deal"><div className="best-image">{best.property.aerialUrl ? <img src={best.property.aerialUrl} alt={`Aerial imagery of ${best.property.address}`}/> : <div className="image-missing">Aerial unavailable</div>}<span>#1 modeled deal</span></div><div className="best-copy"><p className="eyebrow">IF I WERE SCREENING THESE FOR MYSELF</p><h2>{best.property.address}</h2><p>I would investigate this one first—not buy it blindly. It currently has the strongest combination of modeled returns, strict location access, sourcing signals, and property-age risk under the shared assumptions below.</p><div className="best-kpis"><div><b>{best.dealScore}</b><span>Deal score</span></div><div><b>{best.tenYearIrr.toFixed(1)}%</b><span>10-year IRR</span></div><div><b>{best.dscr.toFixed(2)}×</b><span>DSCR</span></div><div><b className={`grade grade-${best.property.locationGrade.toLowerCase()}`}>{best.property.locationGrade}</b><span>Harsh location grade</span></div></div><p className="location-verdict"><b>{best.property.locationTier}:</b> {best.property.locationScore}/100. Only scores of 72+ receive an A; outer-area access is penalized.</p><div className="best-actions"><a className="primary" href={`/analyze?parcel=${best.property.parcelId}`}>Underwrite #1 →</a><a href={best.property.evidenceUrl} target="_blank" rel="noreferrer">Municipal record ↗</a></div></div></section>}
      <section className="rank-summary"><div><span>Deals ranked</span><strong>{ranked.length.toLocaleString()}</strong></div><div><span>Positive cash flow</span><strong>{ranked.filter((deal) => deal.cashFlow > 0).length}</strong></div><div><span>DSCR ≥ 1.20×</span><strong>{ranked.filter((deal) => deal.dscr >= 1.2).length}</strong></div><div><span>Modeled IRR ≥ 12%</span><strong>{ranked.filter((deal) => deal.tenYearIrr >= 12).length}</strong></div></section>
      <section className="harsh-scale"><div><p className="eyebrow">STRICT LOCATION CURVE</p><h2>No participation trophies.</h2><p>A = 72+, B = 60–71, C = 48–59, D = 35–47, and F = below 35. Distance beyond 3.5 miles from every scored demand anchor triggers an additional penalty.</p></div>{["A","B","C","D","F"].map((grade) => <div className={`grade-count grade-${grade.toLowerCase()}`} key={grade}><b>{grade}</b><strong>{ranked.filter((deal) => deal.property.locationGrade === grade).length}</strong><span>properties</span></div>)}</section>
      <section className="panel rank-panel"><div className="panel-head"><div><h2>Ranked opportunity set</h2><p>{excludeCorridors ? "Transit-corridor properties are excluded by default." : "Transit-corridor properties are currently included."} Click any property for full analysis.</p></div><form className="filters"><input name="q" defaultValue={query.q} placeholder="Search property or owner…"/><select name="risk" defaultValue={query.risk ?? "all"}><option value="all">All cash-flow profiles</option><option value="positive">Positive cash flow only</option></select><select name="corridors" defaultValue={query.corridors ?? "exclude"}><option value="exclude">Exclude transit corridors</option><option value="include">Include transit corridors</option></select><select name="yard" defaultValue={query.yard ?? "all"}><option value="all">Any yard potential</option><option value="strong">Strong yard potential</option></select><button>Apply</button></form></div>
        <div className="deal-cards">{ranked.slice(0, 100).map((deal) => <article key={deal.property.parcelId} className="deal-card"><div className="deal-photo">{deal.property.aerialUrl ? <img loading="lazy" src={deal.property.aerialUrl} alt={`Aerial imagery of ${deal.property.address}`}/> : <div className="image-missing">No image</div>}<b>#{deal.rank}</b><span className={deal.cashFlow >= 0 ? "cash-positive" : "cash-negative"}>{deal.cashFlow >= 0 ? "+" : ""}{money.format(deal.cashFlow / 12)}/mo</span></div><div className="deal-body"><div className="deal-title"><div><h3>{deal.property.address}</h3><small>Built {deal.property.yearBuilt ?? "—"} · {money.format(deal.price)} assessment</small></div><strong>{deal.dealScore}<small>/100</small></strong></div><div className="deal-metrics"><div><span>10Y IRR</span><b>{deal.tenYearIrr.toFixed(1)}%</b></div><div><span>Cap rate</span><b>{deal.capRate.toFixed(1)}%</b></div><div><span>DSCR</span><b>{deal.dscr.toFixed(2)}×</b></div><div><span>Debt yield</span><b>{deal.debtYield.toFixed(1)}%</b></div><div><span>Cash-on-cash</span><b>{deal.cashOnCash.toFixed(1)}%</b></div><div><span>Location</span><b>{deal.property.locationScore}/100</b></div></div><div className="location-badges">{deal.property.locationReasons.map((reason) => <span key={reason}>{reason}</span>)}</div><div className="deal-footer"><span className={`risk risk-${deal.risk.toLowerCase().replaceAll(" ", "-")}`}>{deal.risk}</span><p>{deal.thesis}</p><a href={`/analyze?parcel=${deal.property.parcelId}`}>Full analysis →</a></div></div></article>)}</div><p className="table-note">Showing the first 100 ranked properties. Rank is a screening order, not investment advice or an appraisal.</p></section>
      <section id="methodology" className="methodology"><div><p className="eyebrow">AUDITABLE RANKING</p><h2>What drives the recommendation</h2><p>The deal score is 55% modeled financial strength, 25% location access, 15% sourcing opportunity, and 5% building-age risk. Financial strength combines cap rate, DSCR, cash-on-cash return, and 10-year levered IRR.</p></div><div className="assumption-box"><h3>Shared screening assumptions</h3><dl><dt>Monthly fourplex rent</dt><dd>{money.format(DEFAULTS.monthlyRent)}</dd><dt>Financing</dt><dd>{DEFAULTS.downPaymentPct}% down · {DEFAULTS.interestRatePct}% · {DEFAULTS.amortizationYears} years</dd><dt>Variable operating costs</dt><dd>{DEFAULTS.vacancyPct + DEFAULTS.managementPct + DEFAULTS.maintenancePct + DEFAULTS.capexPct}% of gross rent</dd><dt>Rent / value growth</dt><dd>{DEFAULTS.rentGrowthPct}% / {DEFAULTS.appreciationPct}% annually</dd><dt>Exit</dt><dd>Year 10 · {DEFAULTS.sellingCostPct}% selling costs</dd></dl><p>These are assumptions—not property facts. Replace them in Buy Lab before relying on a result.</p></div></section>
    </main></div>;
}
